### ISSUE TITLE
Components Overrides not working in MUI 5

### ISSUE THREAD

**Issue by kkaplita** [gregnb/mui-datatables#1880]
Components Overrides not working i MUI 5
![image](https://user-images.githubusercontent.com/34654152/156757484-a34ec5f4-ee40-4712-bc58-5656f2a328df.png)

## Expected Behavior
Overrides should work (but defined in theme)

## Current Behavior
Overrides in MUI 5 not working.

| Tech         | Version |
|--------------|---------|
| Material-UI  |    5.3.0     |
| MUI-datatables  |    4.1.2     |
| React        |    17.0.2     |
| browser      |    any     |

**Comment by Simrut** [comment]
I have the same problem, downgraded MUI to v4 for now and used such an override`const getMuiTheme = () =>
  createMuiTheme({
    overrides: {
      MUIDataTable: {
        root: {
          backgroundColor: "#FF000",
        },
      },
      MUIDataTableBodyCell: {
        root: {
          width: "200px",
        },
      },
    },
  });`
This is deprecated however

**Comment by macevedoinf** [comment]
I'm having the same issue. I think it must be related to the CSS class generation. If you inspect the DOM elements you won't see any class plain as `MUIDataTableBodyCell-root` in this picture you can see `tss-1qtl85h-MUIDataTableBodyCell-root` as you can see in the following picture.

![image](https://user-images.githubusercontent.com/7191000/161890237-329ed35e-d1fe-4f01-bded-95d7bc880cf8.png)

**Comment by GabrielPRomero** [comment]
Hey, if you using css or styled components. You can try this, example if it is a div:

Styled component:
const StyledDataTable = styled(MUIDataTable)({ '& div[class*="MUIDataTableFilterList-root"]': { maxHeight: none, // add your style }, });

css:
div[class*="MUIDataTableFilterList-root"]': {
maxHeight: none,
// add your style
},

**Comment by ashfaqnisar** [comment]
Hey @kkaplita,  this issue has been fixed in the  newest release 4.2.2.  Please take a look whether this fixed you're issue.

**Comment by FlaviusBejan** [comment]
In my case when the table is rendered, the CSS is injected above the one for all the components. This breaks everything.
I've hidden the data showed on the rows and in the table.
![Screenshot_5](https://user-images.githubusercontent.com/8842356/166479555-40dcf77f-edc1-410e-97aa-bce26c0d3b26.png)
![Screenshot_7](https://user-images.githubusercontent.com/8842356/166479566-5ff05af4-675b-4f17-8e40-8066d2e01b73.png)

**Comment by FlaviusBejan** [comment]
I'm not sure if this is related to the problem.
I've changed from the latest @emotion/styled 11.8.1 to 11.6.0 and the problem was solved.
I don't know how and why, but all the other mui components worked fine with 11.8.1 and only when the table was rendered everything was broken.
I've realized this when trying to do a demo in CodeSandbox. which failed with `(0 , $csb___emotion_utils.registerStyles) is not a function`. Changing to 11.6.0 removed the problem.
https://codesandbox.io/s/silly-goldstine-4lgfwi?file=/package.json
The solution was found here: https://github.com/mui/material-ui/issues/31149
